## Матричный метод

In [1]:
import numpy as np

решение системы линейных алгебраических уравнений по матричному методу определяется равенство
$X=A^{-1}*B$

В случае, если det A не равен нулю, у системы имеется только один вариант решения: при помощи метода обратной матрицы. Если det A=0, то систему нельзя решить данным методом.

Создадим и заполним матрицу

In [2]:
A = np.matrix('9 1 2; 5 2 1; 7 7 4')
B = np.matrix('3; 9; 2')
print("Матрица A:\n", A)
print("\nСтолбец свободных коэффициентов B:\n", B)

Матрица A:
 [[9 1 2]
 [5 2 1]
 [7 7 4]]

Столбец свободных коэффициентов B:
 [[3]
 [9]
 [2]]


In [3]:
if round(np.linalg.det(A), 3) != 0: 
    A_inv = np.linalg.inv(A)
    R = A_inv.dot(B) 
    i = 1
    for elem in R: 
        print(f"x{i} = {elem}") 
        i += 1
else:
    print("Определитель равен 0, систему решить нельзя")

x1 = [[2.28947368]]
x2 = [[4.23684211]]
x3 = [[-10.92105263]]


## Метод крамера 

Для решения системы линейных уравнений методом Крамера из коэффициентов при неизвестных составляется главный определитель системы

Создадим и заполним матрицу

In [4]:
A = np.matrix('7 1 0; 5 4 2; 7 5 3')
B = np.matrix('5; 1; 4')
print("Матрица A:\n", A)
print("\nСтолбец свободных коэффициентов B:\n", B)

Матрица A:
 [[7 1 0]
 [5 4 2]
 [7 5 3]]

Столбец свободных коэффициентов B:
 [[5]
 [1]
 [4]]


In [5]:
if round(np.linalg.det(A), 3) != 0:
    C = A.copy() 
    C[:, 0] = B[:, 0] 
    x1 = round(np.linalg.det(C), 3) / round(np.linalg.det(A), 3)
    F = A.copy()  
    F[:, 1] = B[:, 0] 
    x2 = round(np.linalg.det(F), 3) / round(np.linalg.det(A), 3) 
    J = A.copy() 
    J[:, 2] = B[:, 0] 
    x3 = round(np.linalg.det(J), 3) / round(np.linalg.det(A), 3) 
   
    print("x1:", x1, "x2:", x2, "x3:", x3)

x1: 1.1538461538461537 x2: -3.076923076923077 x3: 3.769230769230769
