In [1]:
import numpy as np

##### Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [2]:
A=np.matrix('45 15 6; 7 4 6; 3 34 16')
p=3
q=7
L=(p+q)*A
R=p*A+q*A
print(f"L= {L}")
print(f"R= {R}")

L= [[450 150  60]
 [ 70  40  60]
 [ 30 340 160]]
R= [[450 150  60]
 [ 70  40  60]
 [ 30 340 160]]


##### Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [3]:
A = np.matrix('9 18 2; 4 13 4')
B = np.matrix('5 6 26; 4 47 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(f"L= {L}")
print(f"R= {R}")

L= [[ 42  72  84]
 [ 24 180  36]]
R= [[ 42  72  84]
 [ 24 180  36]]


##### Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [4]:
A = np.matrix('11 23 4 ; 21 3 4')
B = np.matrix('25 32 6; 7 11 28')
C = np.matrix('1 22 7; 19 23 3')
L = A + (B + C)
R = (A + B) + C

##### При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [5]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(f"A= {A}")
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(f"B= {B}")
print(round(np.linalg.det(A),3))
print(round(np.linalg.det(B),3))

A= [[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
B= [[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]
-14.0
14.0


##### Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [6]:
A=np.matrix('5 11 2 6; 10 4 4 1; 8 33 1 6;7 8 3 21')
print(A)
print(A.T)

[[ 5 11  2  6]
 [10  4  4  1]
 [ 8 33  1  6]
 [ 7  8  3 21]]
[[ 5 10  8  7]
 [11  4 33  8]
 [ 2  4  1  3]
 [ 6  1  6 21]]


In [7]:
det_A=round(np.linalg.det(A),3)
det_A_t=round(np.linalg.det(A.T),3)
print(det_A)
print(det_A_t)

3156.0
3156.0


##### Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [8]:
A = np.matrix('8. 6.; -4. 6.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.08333333  0.05555556]
 [-0.08333333  0.11111111]]
[[ 0.08333333  0.05555556]
 [-0.08333333  0.11111111]]


##### Обратная матрица произведения матриц равна произведению обратных матриц:

In [9]:
A=np.matrix('4. 1.; -2. 16.')
B=np.matrix('-7. 6.;1. -8.')
L=np.linalg.inv(A.dot(B))
R=np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[-0.04242424 -0.00484848]
 [-0.00909091 -0.00818182]]
[[-0.04242424 -0.00484848]
 [-0.00909091 -0.00818182]]


#####  Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю

In [10]:
A=np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


0.0